PARAMETER lp.

WAIT UNTIL ((VXCL(SHIP:UP:FOREVECTOR, lp:POSITION):MAG < 300) OR (VANG(VXCL(SHIP:UP:FOREVECTOR, SHIP:VELOCITY:SURFACE), VXCL(SHIP:UP:FOREVECTOR, lp:POSITION - VXCL(SHIP:UP:FOREVECTOR, SHIP:VELOCITY:SURFACE):NORMALIZED * (SHIP:GROUNDSPEED + SHIP:GROUNDSPEED ^ 2 / (SHIP:MAXTHRUST / SHIP:MASS)))) > 90)).
IF NOT BRAKES { TOGGLE BRAKES. }
LOCK STEERING TO -SHIP:VELOCITY:SURFACE + VXCL(SHIP:UP:FOREVECTOR, -SHIP:VELOCITY:SURFACE)*3.
WAIT 2.
LOCK THROTTLE TO SHIP:GROUNDSPEED / 30.
WAIT UNTIL SHIP:GROUNDSPEED < 2.5.
LOCK THROTTLE TO 0.
