WAIT 5.

SET lp TO SHIP:GEOPOSITION.
LOCK STEERING TO HEADING(90,88).
COPYPATH("0:touchdown", "touchdown").
COPYPATH("0:glideTowards", "glideTowards").
LOCK THROTTLE TO 1.
STAGE.
TOGGLE GEAR.
WAIT UNTIL ORBIT:APOAPSIS > 20000.
TOGGLE RCS.
LOCK THROTTLE TO 0.
WAIT UNTIL SHIP:VERTICALSPEED < 0.
run glideTowards(lp).
PRINT "LANDING SEQUENCE".
RUN TOUCHDOWN(lp).
SET SHIP:CONTROL:PILOTMAINTHROTTLE TO 0.
LOCK THROTTLE TO 0.
